### ISSUE TITLE
htmldjango language server is not starting 

### ISSUE THREAD

**Issue by nikovlod** [yaegassy/coc-htmldjango#14]
htmldjango is not providing any completion in .htmldjango files.
I am unable to figure out the problem. I installed it using cocinstall. please help.

**Comment by yaegassy** [comment]
coc-htmldjango does not use a Language Server. Is your problem that the extension is not activated?

> htmldjango is not providing any completion in .htmldjango files.

coc-htmldjango is enabled for `htmldjango` filetypes. Check the filetype of the current file. Try `:echo &filetype`.

It does not work with `*.htmldjango` file names. Check Vim/Neovim help for filetype. `:help filetype`

**Comment by nikovlod** [comment]
it's working now. thanks 😊
