### ISSUE TITLE
Error on notification "runCommand": Command: htmldjango.showOutput not found

### ISSUE THREAD

**Issue by jjmurre** [yaegassy/coc-htmldjango#16]
I am getting this error on `CocCommand htmldjango.showOutput`. Where should I look to see what is wrong?

**Comment by jjmurre** [comment]
I tried `CocUninstall coc-htmldjango` and installing it again. But that did not help.

**Comment by yaegassy** [comment]
coc-htmldjango works only with `htmldjango` filetypes. If you want to force the file type to `htmldjango`, try `:set ft=htmldjango`.

**Comment by jjmurre** [comment]
That was really the missing link! Now it works, tx!!
