### ISSUE TITLE
Timeouts on larger files

### ISSUE THREAD

**Issue by adinhodovic** [yaegassy/coc-htmldjango#38]
Hey, not a bug in this repository most likely but looking for a solution. Djlint is very slow on larger files and CoC seems to have a 500ms timeout. How can I disable auto formatting on save. And enable formatting by calling `CocAction` that does not have a timeout.

```
au BufWrite *.html call CocAction('format')
```

And setting the provider to none:

```
"htmldjango.formatting.provider": "none",
```

Disables autoformatting on save that has the timeout, but also removes the formatting provider which makes the format action illegible. Is there some other flag to disable formatting? Or any other solution?

Thanks!

**Comment by yaegassy** [comment]
If you want coc.nvim to automatically perform formatting when saving a file, set the following in `coc-settings.json`.

This is an example of an `htmldjango` file type.

```jsonc
{
  "[htmldjango]": {
    "coc.preferences.formatOnSave": true
  }
}
```

Set to `false` to disable automatic formatting.

```jsonc
{
  "[htmldjango]": {
    "coc.preferences.formatOnSave": false
  }
}
```

**Comment by adinhodovic** [comment]
Thanks a lot @yaegassy !
