### ISSUE TITLE
djlint tabWidth

### ISSUE THREAD

**Issue by robphoenix** [yaegassy/coc-htmldjango#8]
Hi, would it be possible to be able to set the `tabWidth` for the djlint format command? Thanks.

**Comment by yaegassy** [comment]
Hi, In "djlint", the indent size seems to be set in `pyproject.toml`.

- <https://djlint.com/djlint/configuration.html>

I think it would be very useful to provide an option for indent size in cli. e.g. `--indent 2`

If "djlint" itself adds options for cli, then `coc-htmldjango` can also add configuration options. I think it would be a good idea to submit a feature request to djlint.

**Comment by yaegassy** [comment]
I'll find time later to add a feature `--indent` option in djlint 🙇

**Comment by robphoenix** [comment]
Many thanks @yaegassy 🙏🏻

**Comment by yaegassy** [comment]
Added the option `htmldjango.djlint.indent`.

1. Update coc-htmldjango
   - `:CocUpdate`
2. Run a command to update the tool, such as djlint
   - `:CocCommand htmldjango.builtin.installTools`

**Comment by robphoenix** [comment]
Works a charm, thankyou so much 🙏🏻 ❤️
